[versions]
# libraries
annotations = "26.0.2-1"
kotlinxSerialization = "1.10.0"
junit = "4.13.2"
reflections = "0.10.2"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.10"
kover = "0.9.6"
qodana = "2025.3.1"

[libraries.annotations]
group = "org.jetbrains"
name = "annotations"
version.ref = "annotations"

[libraries.kotlinxSerialization]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinxSerialization"

[libraries.junit]
group = "junit"
name = "junit"
version.ref = "junit"

[libraries.reflections]
group = "org.reflections"
name = "reflections"
version.ref = "reflections"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"

[plugins.intelliJPlatform]
id = "org.jetbrains.intellij.platform"
version.ref = "intelliJPlatform"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.kover]
id = "org.jetbrains.kotlinx.kover"
version.ref = "kover"

[plugins.qodana]
id = "org.jetbrains.qodana"
version.ref = "qodana"

[plugins.kotlinSerialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"
